// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2x5J01XHoES2gI7Y8iPAAVh6J02jliCw',
    appId: '1:231387204330:web:cf3bd97a5b6907a128a593',
    messagingSenderId: '231387204330',
    projectId: 'mi-reina-b3230',
    authDomain: 'mi-reina-b3230.firebaseapp.com',
    storageBucket: 'mi-reina-b3230.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApHWEqKpjqm7m0MPYvZ4FXGmbcL5tr9R0',
    appId: '1:231387204330:android:26ff7cb6f194bc7628a593',
    messagingSenderId: '231387204330',
    projectId: 'mi-reina-b3230',
    storageBucket: 'mi-reina-b3230.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxudoJXEMsTdgeqD8ZlWy-KWDR8_JF6dc',
    appId: '1:231387204330:ios:80d4d964ba6a999d28a593',
    messagingSenderId: '231387204330',
    projectId: 'mi-reina-b3230',
    storageBucket: 'mi-reina-b3230.firebasestorage.app',
    iosBundleId: 'com.example.miReina',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2x5J01XHoES2gI7Y8iPAAVh6J02jliCw',
    appId: '1:231387204330:web:5a0dc566f4157a3228a593',
    messagingSenderId: '231387204330',
    projectId: 'mi-reina-b3230',
    authDomain: 'mi-reina-b3230.firebaseapp.com',
    storageBucket: 'mi-reina-b3230.firebasestorage.app',
  );
}
